-- PROCEDIMIENTOS ALMACENADOS - EN POSTGRESQL LLAMADAS FUNCIONES
-- ESTA FUNCION MOSTRARA LOS DATOS DE LA CITAS MEDICAS MEDIANTE EL ID DEL PACIENTE 

-- EN POSTGRESQL LOS PROCEDIMIENTOS ALMACENADOS SE REALIZAN A TRAVES DE FUNCIONES
	-- LOS PARAMETROS DE ESTA FUNCION SON DE 2 TIPOS "IN" PARAMETROS QUE RECIBE LA FUNCION Y "OUT" PARAMETROS QUE RETORNA LA FUNCION
CREATE OR REPLACE FUNCTION CitasPorPacientes(
		IN INTEGER, 
        OUT ID_PACIENTE INTEGER,OUT NOMBRE_PACIENTE CHARACTER VARYING, OUT APELLIDO_PACIENTE CHARACTER VARYING, 
		OUT NOMBRE_DOCTOR CHARACTER VARYING, OUT APELLIDO_DOCTOR CHARACTER VARYING, OUT ESPECIALIDAD_DOCTOR CHARACTER VARYING,
		OUT FECHA DATE, OUT HORA TIME)
RETURNS SETOF RECORD AS
$BODY$
       BEGIN
	   -- CONSULTA QUE EJECUTARA ESTA FUNCION
             RETURN QUERY
             SELECT P.ID, P.NOMBRE, P.APELLIDO, D.NOMBRE, D.APELLIDOS, D.ESPECIALIDAD, C.FECHA, C.HORA
             FROM PUBLIC.CITAS C
			 INNER JOIN PUBLIC.PACIENTE P
			 ON P.ID = C.ID_PACIENTE
			 INNER JOIN PUBLIC.DOCTOR D
			 ON D.ID = C.ID_DOCTOR
			 WHERE C.ID_PACIENTE=$1;
       END;
$BODY$
LANGUAGE PLPGSQL VOLATILE
COST 100
ROWS 1000;

-- EJECUCION DE LA FUNCION, RECIBE COMO PARAMETRO EL ID DE UN PACIENTE
SELECT * FROM CitasPorPacientes(2);

SELECT * FROM PUBLIC.DOCTOR